# Generated by Django 5.0.1 on 2024-01-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_truck_sub_catalog_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='truck_type',
            new_name='type',
        ),
    ]
